function cfg = config()
%CONFIG Create configuration structure for zonotope-based EV flexibility study.
%   cfg = CONFIG() returns a struct containing random seeds, discretisation
%   settings, per-segment behavioural parameters, normalisation constants and
%   solver options used throughout the project.
%
%   Output
%   ------
%   cfg : struct
%       Configuration structure adhering to the experiment specification.
%
%   Example
%   -------
%   cfg = config();
%   disp(cfg.seg.Private.weight);
%
%   See also SIMULATE_EV_DATASET

arguments
end

cfg = struct();

cfg.seed = 2025;
cfg.tgrid = 0:2:24;
cfg.Nwin = numel(cfg.tgrid) - 1;
cfg.N_users = 1680;

segNames = {"Private","TNC","Taxi","Corp","Bus"};
weights = [0.60, 0.15, 0.10, 0.10, 0.05];
assert(abs(sum(weights) - 1.0) <= 1e-9, 'Segment weights must sum to 1.');

cfg.seg = struct();

cfg.seg.Private = struct( ...
    'weight', weights(1), ...
    'Cap_max_rng', [50, 80], ...
    'Cap_min_ratio', 0.12, ...
    'Pu_rng', [3.3, 7.4], ...
    'V2G_rate', 0.30, ...
    'Pd_rng', [3, 6], ...
    't_in_mog_params', struct( ...
        'mu', {19.5, 8.0}, ...
        'sigma', {1.5, 1.0}, ...
        'weight', {0.7, 0.3}), ...
    'T_in_rng', struct('type', 'uniform', 'bounds', [9, 12]), ...
    'Cap_in_beta', [2, 4], ...
    'Cap_exp_rule', struct('ratio', 0.80, 'tolerance', 0.02) ...
    );

cfg.seg.TNC = struct( ...
    'weight', weights(2), ...
    'Cap_max_rng', [55, 85], ...
    'Cap_min_ratio', 0.10, ...
    'Pu_rng', [7, 11], ...
    'V2G_rate', 0.50, ...
    'Pd_rng', [3, 7], ...
    't_in_mog_params', struct( ...
        'mu', {2.0, 13.0, 21.0}, ...
        'sigma', {1.0, 1.5, 1.0}, ...
        'weight', {0.3, 0.4, 0.3}), ...
    'T_in_rng', struct('type', 'uniform', 'bounds', [2, 4]), ...
    'Cap_in_beta', [2, 5], ...
    'Cap_exp_rule', struct('ratio', 0.65, 'tolerance', 0.02) ...
    );

cfg.seg.Taxi = struct( ...
    'weight', weights(3), ...
    'Cap_max_rng', [40, 70], ...
    'Cap_min_ratio', 0.10, ...
    'Pu_rng', [11, 22], ...
    'V2G_rate', 0.70, ...
    'Pd_rng', [7, 11], ...
    't_in_mog_params', struct( ...
        'mu', {1.0, 11.5}, ...
        'sigma', {0.8, 1.2}, ...
        'weight', {0.4, 0.6}), ...
    'T_in_rng', struct('type', 'mixture_uniform', ...
        'weights', [0.6, 0.4], ...
        'bounds', [1, 3; 4, 6]), ...
    'Cap_in_beta', [1.5, 5], ...
    'Cap_exp_rule', struct('ratio', 0.60, 'tolerance', 0.02) ...
    );

cfg.seg.Corp = struct( ...
    'weight', weights(4), ...
    'Cap_max_rng', [50, 75], ...
    'Cap_min_ratio', 0.12, ...
    'Pu_rng', [6.6, 22], ...
    'V2G_rate', 0.40, ...
    'Pd_rng', [3, 11], ...
    't_in_mog_params', struct( ...
        'mu', {9.0, 18.0}, ...
        'sigma', {1.0, 1.2}, ...
        'weight', {0.8, 0.2}), ...
    'T_in_rng', struct('type', 'uniform', 'bounds', [7, 10]), ...
    'Cap_in_beta', [2.5, 3.5], ...
    'Cap_exp_rule', struct('ratio', 0.75, 'tolerance', 0.02) ...
    );

cfg.seg.Bus = struct( ...
    'weight', weights(5), ...
    'Cap_max_rng', [220, 320], ...
    'Cap_min_ratio', 0.20, ...
    'Pu_rng', [50, 120], ...
    'V2G_rate', 1.00, ...
    'Pd_rng', [30, 60], ...
    't_in_mog_params', struct( ...
        'mu', {0.5, 23.0}, ...
        'sigma', {0.6, 0.7}, ...
        'weight', {0.5, 0.5}), ...
    'T_in_rng', struct('type', 'uniform', 'bounds', [5, 7]), ...
    'Cap_in_beta', [3, 3], ...
    'Cap_exp_rule', struct('ratio', 0.90, 'tolerance', 0.01) ...
    );

cfg.seg_names = segNames;

cfg.norm = struct( ...
    't_min', 0.0, ...
    't_max', 24.0, ...
    'E_min', 0.0, ...
    'E_max', 350.0, ...
    'eps', 1e-6 ...
    );

t_span = max(cfg.norm.t_max - cfg.norm.t_min, eps);
e_span = max(cfg.norm.E_max - cfg.norm.E_min, eps);
cfg.norm.scale_t = 1.0 / t_span;
cfg.norm.scale_E = 1.0 / e_span;
cfg.norm.offset = [cfg.norm.t_min; cfg.norm.E_min];

cfg.use_improved_generators = true;

cfg.linprog_opts = optimoptions('linprog', ...
    'Algorithm', 'dual-simplex', ...
    'Display', 'none');

cfg.parallel = struct('use_parallel', false);

cfg.validation = struct('min_cap_max', 40, 'max_cap_max', 350);

assert(all(isfield(cfg.seg, segNames)), 'All segment descriptors must be defined.');

end
